<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Coin extends Model
{
    protected $fillable = ['id','coin_id','name', 'symbol', 'image', 'current_price', 'price_change_percentage_24h', 'market_cap'];
    public $incrementing = false;
    public function bootIfNotBooted()
    {
        parent::bootIfNotBooted(); // TODO: Change the autogenerated stub

        static::creating(function ($model) {
            $model->id = Str::uuid();
        });
    }
}
